# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Fri, 25 Nov 2016 20:59:10 +0000
*               @ALL          1
*               @user         8
