<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: dtconfect
 * Date: Tue, 10 Jan 2017 18:52:56 +0000
 */

$conf['title'] = 'Marlien Wiki';
$conf['template'] = 'monobook';
$conf['useheading'] = 'content';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';

// end auto-generated content
