<?php
/*
 * Local plugin enable/disable settings
 *
 * Auto-generated by install script
 * Date: Fri, 25 Nov 2016 20:59:10 +0000
 */

$plugins['authad']    = 0;
$plugins['authldap']  = 0;
$plugins['authmysql'] = 0;
$plugins['authpgsql'] = 0;
